### ISSUE TITLE
Exception in thread "main" java.lang.NoClassDefFoundError: com/apple/eawt/AboutHandler

### ISSUE THREAD

**Issue by limitLiu** [ice1000/dev-kt#10]
<img width="586" alt="QQ20190909-184632@2x" src="https://user-images.githubusercontent.com/18195954/64524935-3efb6880-d332-11e9-900e-354435dde923.png">

<img width="947" alt="QQ20190909-184606@2x" src="https://user-images.githubusercontent.com/18195954/64524954-491d6700-d332-11e9-9aa8-b68f57ce6d00.png">

**Comment by ice1000** [comment]
Similar issue triplea-game/triplea#3297
Official reported issue http://openjdk.java.net/jeps/272

**Comment by ice1000** [comment]
https://github.com/ice1000/dev-kt/blob/master/swing/src/lie/mac.kt

**Comment by ice1000** [comment]
Maybe we should not have Mac-specific support.
