### ISSUE TITLE
No editing capability.

### ISSUE THREAD

**Issue by b4apple** [ice1000/dev-kt#13]
I downloaded the dev-kt jar from the provided link on a Windows machine. I created a new file successfully where a sample hello world program with NO SYNTAX HIGHLIGHTING appeared. I selected the enitre text with Ctrl-A and deleted it. When I tried writing my own program, no text was appearing in the editor. And also, there was some button in the bottom-right corner of the screen which kept showing 10 of 34M or something similar.

**Comment by ice1000** [comment]
I don't understand. If you write a pure text file, what syntax highlight would you expect?

Btw, the button shows the current memory size of the JVM heap. Clicking the button invokes `System.gc()`.

**Comment by ice1000** [comment]
Try to learn how to describe your issue (or how to talk to people) before complaining.

**Comment by b4apple** [comment]
I clicked the create a new Kotlin file option in the file menu. It gave me the default Hello World file with NO syntax highlighting. I don't think your application options create a plain text file. And I couldn't write my own text in it.  See this : https://drive.google.com/file/d/1mbW--oAjdcX26DhjN-d5uqRIq1jZJpWw/view This is what is happening. At the end, the cursor is blinking though I am frantically pressing the keys on the keyboard to get my code on the screen.

**Comment by ice1000** [comment]
I cannot access the file, it's private

**Comment by ice1000** [comment]
Ok, now I see the issue. Try this option.

![image](https://user-images.githubusercontent.com/16398479/116188626-5337e780-a75a-11eb-9d51-6b0a1b3a1949.png)

**Comment by ice1000** [comment]
If you want to use Kotlin highlighting, use the option or try to save your file to a file with `.kt` extension.
