### ISSUE TITLE
Plugin support for wangyang2010344/S-Lisp

### ISSUE THREAD

**Issue by wangyang2010344** [ice1000/dev-kt#7]
主页在这，[https://gitee.com/wy2010344/S-Lisp](https://gitee.com/wy2010344/S-Lisp)，示例也可以看看[https://gitee.com/wy2010344/S-Lisp/blob/master/C++/S/test/t.lisp](https://gitee.com/wy2010344/S-Lisp/blob/master/C++/S/test/t.lisp)。（不太会用Issues）

**Comment by ice1000** [comment]
https://github.com/ice1k/s-lisp-intellij

**Comment by ice1000** [comment]
![s-lisp](https://user-images.githubusercontent.com/16398479/43755214-e8b689da-99dc-11e8-926f-8ac42f40c794.gif)

**Comment by ice1000** [comment]
[s-lisp-intellij-0.1.zip](https://github.com/ice1000/dev-kt/files/2265022/s-lisp-intellij-0.1.zip)

把这个拖到你的鸡巴里，然后点重启鸡巴就可以用了。DevKt的我明天再移植，晚安

**Comment by ice1000** [comment]
https://github.com/ice1k/s-lisp-intellij/releases/tag/v0.1

**Comment by wangyang2010344** [comment]
感谢大佬！感谢感谢！

**Comment by wangyang2010344** [comment]
thanks very much!

**Comment by wangyang2010344** [comment]
thanks very much!

**Comment by ice1000** [comment]
.
